name: logiruta
description: LogiRuta - Gestión Logística Inteligente
publish_to: 'none'
version: 1.0.0+7  # Formato: version+buildNumber (se muestra como 1.0.0.6)

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.5
  flutter_secure_storage: ^9.2.4
  animated_bottom_navigation_bar: ^1.3.0
  animate_do: ^4.2.0
  shared_preferences: ^2.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
